comment:
  require_changes: true

flags:
  api:
    paths:
      - api/
    carryforward: true
  web:
    paths:
      - web/
    carryforward: true
  gateway:
    paths:
      - gateway/
    carryforward: true
