// Files exempt from the ui/* rules until their domain is migrated.
// Each domain PR deletes its section; delete this file once it is empty.
// Entries are globs, so route brackets are escaped.
export const legacyUiFiles = [
  // games + games dashboard
  'app/dashboard/games/\\[token\\]/library/page.tsx',
  'app/dashboard/games/\\[token\\]/page.tsx',
  'app/dashboard/games/page.tsx',
  'app/games/\\[id\\]/SteamGameClient.tsx',
  'app/games/distribution/\\[bucket\\]/SteamDistributionClient.tsx',
  'app/games/library/page.tsx',
  'components/dashboard/GamesDashboard.tsx',
  'components/dashboard/GamesDashboardPublicClient.tsx',
  'components/dashboard/GamesDashboardPublicGameClient.tsx',
  'components/dashboard/GamesDashboardPublicLibrary.tsx',
  'components/games/AchievementCard.tsx',
  'components/games/GameCards.tsx',
  'components/games/GamesDashboardView.tsx',
  'components/games/GamesLibrary.tsx',
  'components/games/GamesSearch.tsx',
  'components/games/GamesSettingsClient.tsx',
  'components/games/GamesStatsPanel.tsx',
  'components/games/SteamDistributionChart.tsx',
  // feeds
  'app/feeds/health/page.tsx',
  'app/feeds/page.tsx',
  'app/feeds/settings/page.tsx',
  'app/feeds/stats/page.tsx',
  'components/ArticleReaderDialog.tsx',
  'components/dashboard/SharedFeedsCard.tsx',
  'components/feeds/AddFeedForm.tsx',
  'components/feeds/ArticleReaderDialog.tsx',
  'components/feeds/FeedList.tsx',
  'components/feeds/FeedManager.tsx',
  'components/feeds/FeedReaderClient.tsx',
  'components/feeds/FeedStatsClient.tsx',
  'components/feeds/FeedsCard.tsx',
  'components/feeds/FeedsHeader.tsx',
  // recipes, mealplans, shoppinglist
  'app/mealplans/\\[id\\]/MealPlanClient.tsx',
  'app/mealplans/\\[id\\]/edit/EditPlanClient.tsx',
  'app/recipes/\\[id\\]/RecipeClient.tsx',
  'app/recipes/\\[id\\]/edit/EditRecipeClient.tsx',
  'app/recipes/new/page.tsx',
  'app/shoppinglist/settings/page.tsx',
  'components/mealplans/MealPlanCalendar.tsx',
  'components/mealplans/MealPlanEntryForm.tsx',
  'components/mealplans/MealPlanMealChip.tsx',
  'components/mealplans/MealPlanWeekGrid.tsx',
  'components/mealplans/PlanForm.tsx',
  'components/mealplans/PlansListClient.tsx',
  'components/recipes/RecipeForm.tsx',
  'components/recipes/RecipesListClient.tsx',
  'components/shoppinglist/AddItemForm.tsx',
  'components/shoppinglist/CategoryManager.tsx',
  'components/shoppinglist/ExportDialog.tsx',
  'components/shoppinglist/ItemCatalog.tsx',
  'components/shoppinglist/MealPlanGroupFilter.tsx',
  'components/shoppinglist/MealPlanItemsPreview.tsx',
  'components/shoppinglist/ShoppingList.tsx',
  'components/shoppinglist/ShoppingListPageClient.tsx',
  'components/shoppinglist/StoreManager.tsx',
  // learningpaths
  'app/learningpaths/\\[id\\]/PathClient.tsx',
  'app/learningpaths/\\[id\\]/edit/EditLearningPathClient.tsx',
  'app/learningpaths/new/page.tsx',
  'components/learningpaths/LearningPathForm.tsx',
  'components/learningpaths/LearningPathsListClient.tsx',
  'components/learningpaths/LearningPathsSettingsClient.tsx',
  'components/learningpaths/ResourceLinkPicker.tsx',
  // trains + watchparty
  'app/watchparty/\\[id\\]/ViewerClient.tsx',
  'app/watchparty/\\[id\\]/presenter/PresenterClient.tsx',
  'app/watchparty/page.tsx',
  'components/trains/JourneyAlternativePanel.tsx',
  'components/trains/JourneyDetailClient.tsx',
  'components/trains/JourneyLegCard.tsx',
  'components/trains/JourneyResults.tsx',
  'components/trains/SavedCommutes.tsx',
  'components/trains/StationField.tsx',
  'components/trains/TrainsClient.tsx',
  // platform pages and shared components
  'app/auth/forgot-password/page.tsx',
  'app/auth/reset-password/page.tsx',
  'app/error.tsx',
  'app/monitoring/connections/page.tsx',
  'app/monitoring/observability/page.tsx',
  'app/settings/page.tsx',
  'components/HomeClient.tsx',
  'components/family/FamilyPageClient.tsx',
  'components/monitoring/AutomatedActionsCard.tsx',
  'components/monitoring/MonitoringSettingsClient.tsx',
  'components/monitoring/OAuthConnectionsCard.tsx',
  'components/monitoring/ProviderConfigDialog.tsx',
  'components/notifications/NotificationToggleList.tsx',
  'components/settings/McpSetupSection.tsx',
  'components/settings/RecoveryCodesDialog.tsx',
  'components/user-management/UserManagementClient.tsx',
  'components/user-management/UsersTable.tsx'
]
