// Files exempt from the ui/* rules until their domain is migrated.
// Each domain PR deletes its section; delete this file once it is empty.
// Entries are globs, so route brackets are escaped.
export const legacyUiFiles = [
  // books + reading dashboard
  'app/books/\\[id\\]/BookDetailClient.tsx',
  'app/books/\\[id\\]/page.tsx',
  'app/books/external/\\[provider\\]/\\[providerId\\]/ExternalBookDetailClient.tsx',
  'app/books/library/page.tsx',
  'app/dashboard/reading/\\[token\\]/library/page.tsx',
  'app/dashboard/reading/\\[token\\]/page.tsx',
  'app/dashboard/reading/page.tsx',
  'components/books/ArticleReaderDialog.tsx',
  'components/books/AuthorBooksClient.tsx',
  'components/books/BookEditDialog.tsx',
  'components/books/BookPreviewDialog.tsx',
  'components/books/BookRatingStars.tsx',
  'components/books/BookReadDatesEditor.tsx',
  'components/books/BookSearchBar.tsx',
  'components/books/BookSourceSync.tsx',
  'components/books/BooksAdminClient.tsx',
  'components/books/BooksDashboardView.tsx',
  'components/books/BooksSection.tsx',
  'components/books/BooksSettingsClient.tsx',
  'components/books/BulkBookUploader.tsx',
  'components/books/ConflictFieldPicker.tsx',
  'components/books/DuplicateBookSummary.tsx',
  'components/books/KoboDeviceLogs.tsx',
  'components/books/KoboDevices.tsx',
  'components/books/KoboGatewayDownload.tsx',
  'components/books/KoboGatewaySetup.tsx',
  'components/books/KoboSyncToggle.tsx',
  'components/books/LibrarySidebar.tsx',
  'components/books/ManageDuplicatesDialog.tsx',
  'components/books/ManageShelvesTagsDialog.tsx',
  'components/books/MarkAsCompletedDialog.tsx',
  'components/books/ResyncWizard.tsx',
  'components/books/SourceCompare.tsx',
  'components/books/SourceStats.tsx',
  'components/dashboard/DashboardBookCard.tsx',
  'components/dashboard/ReadingDashboardPublicClient.tsx',
  'components/dashboard/ReadingDashboardPublicLibrary.tsx',
  // feeds
  'app/feeds/health/page.tsx',
  'app/feeds/page.tsx',
  'app/feeds/settings/page.tsx',
  'app/feeds/stats/page.tsx',
  'components/ArticleReaderDialog.tsx',
  'components/dashboard/SharedFeedsCard.tsx',
  'components/feeds/AddFeedForm.tsx',
  'components/feeds/ArticleReaderDialog.tsx',
  'components/feeds/FeedList.tsx',
  'components/feeds/FeedManager.tsx',
  'components/feeds/FeedReaderClient.tsx',
  'components/feeds/FeedStatsClient.tsx',
  'components/feeds/FeedsCard.tsx',
  'components/feeds/FeedsHeader.tsx',
  // trains + watchparty
  'app/watchparty/\\[id\\]/ViewerClient.tsx',
  'app/watchparty/\\[id\\]/presenter/PresenterClient.tsx',
  'app/watchparty/page.tsx',
  'components/trains/JourneyAlternativePanel.tsx',
  'components/trains/JourneyDetailClient.tsx',
  'components/trains/JourneyLegCard.tsx',
  'components/trains/JourneyResults.tsx',
  'components/trains/SavedCommutes.tsx',
  'components/trains/StationField.tsx',
  'components/trains/TrainsClient.tsx',
  // platform pages and shared components
  'app/auth/forgot-password/page.tsx',
  'app/auth/reset-password/page.tsx',
  'app/error.tsx',
  'app/monitoring/connections/page.tsx',
  'app/monitoring/observability/page.tsx',
  'app/settings/page.tsx',
  'components/HomeClient.tsx',
  'components/family/FamilyPageClient.tsx',
  'components/monitoring/AutomatedActionsCard.tsx',
  'components/monitoring/MonitoringSettingsClient.tsx',
  'components/monitoring/OAuthConnectionsCard.tsx',
  'components/monitoring/ProviderConfigDialog.tsx',
  'components/notifications/NotificationToggleList.tsx',
  'components/settings/McpSetupSection.tsx',
  'components/settings/RecoveryCodesDialog.tsx',
  'components/user-management/UserManagementClient.tsx',
  'components/user-management/UsersTable.tsx'
]
