-- Tracks which PDF/KEPUB converter pipeline version produced a book_files
-- row, so EnsureKEPUB can detect a KEPUB generated by an older, buggy
-- converter and regenerate it instead of serving it forever (issue #594).
-- Existing rows default to 0, which is always stale against any real
-- version >= 1.

-- +goose Up
-- +goose StatementBegin
ALTER TABLE books.book_files
ADD COLUMN converter_version SMALLINT NOT NULL DEFAULT 0;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE books.book_files DROP COLUMN converter_version;
-- +goose StatementEnd
