name: API Lint Workflow

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: API Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: proto-gen-${{ github.run_id }}
      - uses: actions/setup-go@v6
        with:
          go-version-file: './api/go.mod'
          cache-dependency-path: './api/go.sum'
      - run: make lint
        working-directory: './api'
