name: API Lint Workflow

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint-go:
    name: API Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: './api/go.mod'
          cache-dependency-path: './api/go.sum'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.11.3
          working-directory: ./api

  lint-sql:
    name: API SQL Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: sqlfluff-3.3.0
      - name: Install sqlfluff
        run: pip install sqlfluff==3.3.0
      - name: Run sqlfluff
        run: sqlfluff lint --dialect postgres .
        working-directory: './api'
