name: Build Gateway Workflow

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-gateway:
    name: Build Gateway
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - uses: actions/setup-go@v7
        with:
          go-version-file: './gateway/go.mod'
          cache-dependency-path: './gateway/go.sum'
      - run: make build
        working-directory: './gateway'
