name: Gateway Lint Workflow

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint-go:
    name: Gateway Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: './gateway/go.mod'
          cache-dependency-path: './gateway/go.sum'
      - run: make lint
        working-directory: './gateway'
