name: Kobo Gateway Test Workflow

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: Kobo Gateway Test
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: './kobo-gateway/go.mod'
          cache-dependency-path: './kobo-gateway/go.sum'
      - run: make test/cov/report
        working-directory: './kobo-gateway'
      - name: Upload coverage reports to Codecov
        if: always()
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: kobo_gateway
