name: Sentrytools Lint Workflow

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint-go:
    name: Sentrytools Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: './sentrytools/go.mod'
          cache-dependency-path: './sentrytools/go.sum'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          # renovate: datasource=go depName=github.com/golangci/golangci-lint/v2/cmd/golangci-lint
          version: v2.14.0
          working-directory: ./sentrytools
