name: Sentrytools Lint Workflow

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint-go:
    name: Sentrytools Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: './sentrytools/go.mod'
          cache-dependency-path: './sentrytools/go.sum'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          # renovate: datasource=go depName=github.com/golangci/golangci-lint/v2/cmd/golangci-lint
          version: v2.13.1
          working-directory: ./sentrytools
