name: Web Test Workflow

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: Web Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v7
        with:
          cache: 'npm'
          node-version-file: './web/package.json'
          cache-dependency-path: './web/package-lock.json'
      - run: npm ci
        working-directory: './web'
      - run: npm run test:cov
        working-directory: './web'
      - name: Upload coverage reports to Codecov
        if: always()
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: web
