package icsproxy_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"connectrpc.com/connect"
	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	icsproxyv1 "tools.xdoubleu.com/gen/icsproxy/v1"
	"tools.xdoubleu.com/gen/icsproxy/v1/icsproxyv1connect"
)

func newConnectClient(t *testing.T) icsproxyv1connect.ICSProxyServiceClient {
	t.Helper()
	mux := getRoutes()
	ts := httptest.NewServer(mux)
	t.Cleanup(ts.Close)
	return icsproxyv1connect.NewICSProxyServiceClient(http.DefaultClient, ts.URL)
}

// ── ListConfigs ──────────────────────────────────────────────────────────────

func TestListConfigs_Empty(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	resp, err := client.ListConfigs(
		ctx,
		connect.NewRequest(&icsproxyv1.ListConfigsRequest{}),
	)
	require.NoError(t, err)
	// May not be empty if tests share DB state; just verify no errors.
	assert.Empty(t, resp.Msg.Configs)
}

func TestListConfigs_WithConfigs(t *testing.T) {
	// Create a config first (uses same mocked user ID each time)
	client := newConnectClient(t)
	ctx := context.Background()
	token := uuid.NewString()

	srv := calendarServer(t)
	defer srv.Close()

	_, err := client.SaveConfig(ctx, connect.NewRequest(&icsproxyv1.SaveConfigRequest{
		Token:     token,
		SourceUrl: srv.URL,
	}))
	require.NoError(t, err)

	// Now verify the saved config is returned
	resp, err := client.GetConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.GetConfigRequest{
			Token: token,
		}),
	)
	require.NoError(t, err)
	assert.NotNil(t, resp.Msg.Config)
	assert.Equal(t, token, resp.Msg.Config.Token)
}

// ── PreviewEvents ────────────────────────────────────────────────────────────

func TestPreviewEvents_ValidURL(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	srv := calendarServer(t)
	defer srv.Close()

	resp, err := client.PreviewEvents(
		ctx,
		connect.NewRequest(&icsproxyv1.PreviewEventsRequest{
			SourceUrl: srv.URL,
		}),
	)
	require.NoError(t, err)
	require.NotNil(t, resp.Msg.Events)
	assert.Len(t, resp.Msg.Events, 1)
	assert.Equal(t, "test-uid-1", resp.Msg.Events[0].Uid)
	assert.Equal(t, "Team Meeting", resp.Msg.Events[0].Summary)
}

func TestPreviewEvents_EmptyURL(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	_, err := client.PreviewEvents(
		ctx,
		connect.NewRequest(&icsproxyv1.PreviewEventsRequest{
			SourceUrl: "",
		}),
	)
	require.Error(t, err)
	assert.Equal(t, connect.CodeInvalidArgument, connect.CodeOf(err))
}

// ── GetConfig ────────────────────────────────────────────────────────────────

func TestGetConfig_Success(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()
	token := uuid.NewString()

	srv := calendarServer(t)
	defer srv.Close()

	// Save a config
	_, err := client.SaveConfig(ctx, connect.NewRequest(&icsproxyv1.SaveConfigRequest{
		Token:     token,
		SourceUrl: srv.URL,
	}))
	require.NoError(t, err)

	// Get it
	resp, err := client.GetConfig(ctx, connect.NewRequest(&icsproxyv1.GetConfigRequest{
		Token: token,
	}))
	require.NoError(t, err)
	assert.NotNil(t, resp.Msg.Config)
	assert.Equal(t, token, resp.Msg.Config.Token)
	assert.Len(t, resp.Msg.Events, 1)
}

func TestGetConfig_NotFound(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	_, err := client.GetConfig(ctx, connect.NewRequest(&icsproxyv1.GetConfigRequest{
		Token: "nonexistent",
	}))
	require.Error(t, err)
	assert.Equal(t, connect.CodeNotFound, connect.CodeOf(err))
}

// ── SaveConfig ───────────────────────────────────────────────────────────────

func TestSaveConfig_AutoGeneratedToken(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	srv := calendarServer(t)
	defer srv.Close()

	resp, err := client.SaveConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.SaveConfigRequest{
			Token:     "",
			SourceUrl: srv.URL,
		}),
	)
	require.NoError(t, err)
	assert.NotEmpty(t, resp.Msg.Token)

	// Verify it was saved
	getResp, err := client.GetConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.GetConfigRequest{
			Token: resp.Msg.Token,
		}),
	)
	require.NoError(t, err)
	assert.Equal(t, resp.Msg.Token, getResp.Msg.Config.Token)
}

func TestSaveConfig_ExplicitToken(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()
	token := uuid.NewString()

	srv := calendarServer(t)
	defer srv.Close()

	resp, err := client.SaveConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.SaveConfigRequest{
			Token:     token,
			SourceUrl: srv.URL,
		}),
	)
	require.NoError(t, err)
	assert.Equal(t, token, resp.Msg.Token)
}

func TestSaveConfig_WithHideSeries(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()
	token := uuid.NewString()

	srv := calendarServer(t)
	defer srv.Close()

	_, err := client.SaveConfig(ctx, connect.NewRequest(&icsproxyv1.SaveConfigRequest{
		Token:      token,
		SourceUrl:  srv.URL,
		HideSeries: []string{"series-1", "series-2"},
	}))
	require.NoError(t, err)

	// Verify hide_series was saved
	resp, err := client.GetConfig(ctx, connect.NewRequest(&icsproxyv1.GetConfigRequest{
		Token: token,
	}))
	require.NoError(t, err)
	assert.Len(t, resp.Msg.Config.HideSeries, 2)
}

// ── DeleteConfig ─────────────────────────────────────────────────────────────

func TestDeleteConfig_Success(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()
	token := uuid.NewString()

	srv := calendarServer(t)
	defer srv.Close()

	// Save a config
	_, err := client.SaveConfig(ctx, connect.NewRequest(&icsproxyv1.SaveConfigRequest{
		Token:     token,
		SourceUrl: srv.URL,
	}))
	require.NoError(t, err)

	// Delete it
	_, err = client.DeleteConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.DeleteConfigRequest{
			Token: token,
		}),
	)
	require.NoError(t, err)

	// Verify it's gone
	_, err = client.GetConfig(ctx, connect.NewRequest(&icsproxyv1.GetConfigRequest{
		Token: token,
	}))
	require.Error(t, err)
	assert.Equal(t, connect.CodeNotFound, connect.CodeOf(err))
}
