package icsproxy_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"

	"connectrpc.com/connect"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	icsproxyv1 "tools.xdoubleu.com/gen/icsproxy/v1"
	"tools.xdoubleu.com/gen/icsproxy/v1/icsproxyv1connect"
)

func newConnectClient(t *testing.T) icsproxyv1connect.ICSProxyServiceClient {
	t.Helper()
	mux := getRoutes()
	ts := httptest.NewServer(mux)
	t.Cleanup(ts.Close)
	return icsproxyv1connect.NewICSProxyServiceClient(http.DefaultClient, ts.URL)
}

// saveNewConfig creates a feed and returns its server-generated token.
func saveNewConfig(
	t *testing.T,
	client icsproxyv1connect.ICSProxyServiceClient,
	sourceURL string,
) string {
	t.Helper()
	resp, err := client.SaveConfig(
		context.Background(),
		connect.NewRequest(&icsproxyv1.SaveConfigRequest{SourceUrl: sourceURL}),
	)
	require.NoError(t, err)
	require.NotEmpty(t, resp.Msg.Token)
	return resp.Msg.Token
}

// ── ListConfigs ──────────────────────────────────────────────────────────────

func TestListConfigs_Empty(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	resp, err := client.ListConfigs(
		ctx,
		connect.NewRequest(&icsproxyv1.ListConfigsRequest{}),
	)
	require.NoError(t, err)
	// May not be empty if tests share DB state; just verify no errors.
	assert.Empty(t, resp.Msg.Configs)
}

func TestListConfigs_WithConfigs(t *testing.T) {
	// Create a config first (uses same mocked user ID each time)
	client := newConnectClient(t)
	ctx := context.Background()

	srv := calendarServer(t)
	defer srv.Close()

	token := saveNewConfig(t, client, srv.URL)

	// Now verify the saved config is returned
	resp, err := client.GetConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.GetConfigRequest{
			Token: token,
		}),
	)
	require.NoError(t, err)
	assert.NotNil(t, resp.Msg.Config)
	assert.Equal(t, token, resp.Msg.Config.Token)
}

// TestListConfigs_Pagination verifies Limit/Offset bound the page and
// HasMore reflects whether more rows exist beyond it. Configs are ordered
// created_at DESC, so the three freshly-saved configs sort ahead of anything
// other tests may have already created, landing them at offset 0.
func TestListConfigs_Pagination(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	srv := calendarServer(t)
	defer srv.Close()

	for range 3 {
		saveNewConfig(t, client, srv.URL)
	}

	firstPage, err := client.ListConfigs(
		ctx, connect.NewRequest(&icsproxyv1.ListConfigsRequest{Limit: 2}),
	)
	require.NoError(t, err)
	assert.Len(t, firstPage.Msg.Configs, 2)
	assert.True(t, firstPage.Msg.HasMore)

	secondPage, err := client.ListConfigs(
		ctx, connect.NewRequest(&icsproxyv1.ListConfigsRequest{Limit: 2, Offset: 2}),
	)
	require.NoError(t, err)
	assert.NotEmpty(t, secondPage.Msg.Configs)
}

// ── PreviewEvents ────────────────────────────────────────────────────────────

func TestPreviewEvents_ValidURL(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	srv := calendarServer(t)
	defer srv.Close()

	resp, err := client.PreviewEvents(
		ctx,
		connect.NewRequest(&icsproxyv1.PreviewEventsRequest{
			SourceUrl: srv.URL,
		}),
	)
	require.NoError(t, err)
	require.NotNil(t, resp.Msg.Events)
	assert.Len(t, resp.Msg.Events, 1)
	assert.Equal(t, "test-uid-1", resp.Msg.Events[0].Uid)
	assert.Equal(t, "Team Meeting", resp.Msg.Events[0].Summary)
}

func TestPreviewEvents_EmptyURL(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	_, err := client.PreviewEvents(
		ctx,
		connect.NewRequest(&icsproxyv1.PreviewEventsRequest{
			SourceUrl: "",
		}),
	)
	require.Error(t, err)
	assert.Equal(t, connect.CodeInvalidArgument, connect.CodeOf(err))
}

// ── GetConfig ────────────────────────────────────────────────────────────────

func TestGetConfig_Success(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	srv := calendarServer(t)
	defer srv.Close()

	token := saveNewConfig(t, client, srv.URL)

	// Get it
	resp, err := client.GetConfig(ctx, connect.NewRequest(&icsproxyv1.GetConfigRequest{
		Token: token,
	}))
	require.NoError(t, err)
	assert.NotNil(t, resp.Msg.Config)
	assert.Equal(t, token, resp.Msg.Config.Token)
	assert.Len(t, resp.Msg.Events, 1)
}

func TestGetConfig_NotFound(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	_, err := client.GetConfig(ctx, connect.NewRequest(&icsproxyv1.GetConfigRequest{
		Token: "nonexistent",
	}))
	require.Error(t, err)
	assert.Equal(t, connect.CodeNotFound, connect.CodeOf(err))
}

// ── SaveConfig ───────────────────────────────────────────────────────────────

func TestSaveConfig_AutoGeneratedToken(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	srv := calendarServer(t)
	defer srv.Close()

	resp, err := client.SaveConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.SaveConfigRequest{
			Token:     "",
			SourceUrl: srv.URL,
		}),
	)
	require.NoError(t, err)
	assert.NotEmpty(t, resp.Msg.Token)

	// Verify it was saved
	getResp, err := client.GetConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.GetConfigRequest{
			Token: resp.Msg.Token,
		}),
	)
	require.NoError(t, err)
	assert.Equal(t, resp.Msg.Token, getResp.Msg.Config.Token)
}

// A token the caller already owns updates that feed in place.
func TestSaveConfig_ExplicitTokenUpdatesOwnFeed(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	srv := calendarServer(t)
	defer srv.Close()

	token := saveNewConfig(t, client, srv.URL)

	resp, err := client.SaveConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.SaveConfigRequest{
			Token:       token,
			SourceUrl:   srv.URL,
			HolidayUids: []string{"uid-1"},
		}),
	)
	require.NoError(t, err)
	assert.Equal(t, token, resp.Msg.Token)
}

// Feed tokens are the only thing guarding the unauthenticated feed endpoint,
// so a client may not pick one for a feed that doesn't exist yet.
func TestSaveConfig_UnknownTokenRejected(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	srv := calendarServer(t)
	defer srv.Close()

	_, err := client.SaveConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.SaveConfigRequest{
			Token:     "guessable-token",
			SourceUrl: srv.URL,
		}),
	)
	require.Error(t, err)
	assert.Equal(t, connect.CodeNotFound, connect.CodeOf(err))
}

func TestSaveConfig_WithHideSeries(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	srv := calendarServer(t)
	defer srv.Close()

	saveResp, err := client.SaveConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.SaveConfigRequest{
			SourceUrl:  srv.URL,
			HideSeries: []string{"series-1", "series-2"},
		}),
	)
	require.NoError(t, err)
	token := saveResp.Msg.Token

	// Verify hide_series was saved
	resp, err := client.GetConfig(ctx, connect.NewRequest(&icsproxyv1.GetConfigRequest{
		Token: token,
	}))
	require.NoError(t, err)
	assert.Len(t, resp.Msg.Config.HideSeries, 2)
}

// ── feedHandler ──────────────────────────────────────────────────────────────

func TestFeedHandler_TokenNotFound(t *testing.T) {
	ts := httptest.NewServer(getRoutes())
	t.Cleanup(ts.Close)

	resp, err := http.Get(ts.URL + "/icsproxy/unknown-token.ics")
	require.NoError(t, err)
	defer resp.Body.Close()
	assert.Equal(t, http.StatusNotFound, resp.StatusCode)
}

func TestFeedHandler_Success(t *testing.T) {
	client := newConnectClient(t)

	srv := calendarServer(t)
	defer srv.Close()

	token := saveNewConfig(t, client, srv.URL)

	ts := httptest.NewServer(getRoutes())
	t.Cleanup(ts.Close)

	resp, err := http.Get(ts.URL + "/icsproxy/" + token + ".ics")
	require.NoError(t, err)
	defer resp.Body.Close()
	assert.Equal(t, http.StatusOK, resp.StatusCode)
	assert.Contains(t, resp.Header.Get("Content-Type"), "text/calendar")
}

// ── DeleteConfig ─────────────────────────────────────────────────────────────

func TestDeleteConfig_Success(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	srv := calendarServer(t)
	defer srv.Close()

	token := saveNewConfig(t, client, srv.URL)

	// Delete it
	_, err := client.DeleteConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.DeleteConfigRequest{
			Token: token,
		}),
	)
	require.NoError(t, err)

	// Verify it's gone
	_, err = client.GetConfig(ctx, connect.NewRequest(&icsproxyv1.GetConfigRequest{
		Token: token,
	}))
	require.Error(t, err)
	assert.Equal(t, connect.CodeNotFound, connect.CodeOf(err))
}

// TestDeleteConfig_ViaListedToken saves a config, then deletes it using the
// token returned from ListConfigs (as the UI does) rather than the token the
// caller already holds. This is the round trip that previously silently
// no-op'd: the DB stored only a one-way hash of the token, so the value
// ListConfigs handed back could never be used to delete the row it names.
func TestDeleteConfig_ViaListedToken(t *testing.T) {
	client := newConnectClient(t)
	ctx := context.Background()

	srv := calendarServer(t)
	defer srv.Close()

	saveResp, err := client.SaveConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.SaveConfigRequest{SourceUrl: srv.URL}),
	)
	require.NoError(t, err)
	token := saveResp.Msg.Token

	listResp, err := client.ListConfigs(
		ctx,
		connect.NewRequest(&icsproxyv1.ListConfigsRequest{Limit: 100}),
	)
	require.NoError(t, err)

	var listedToken string
	for _, cfg := range listResp.Msg.Configs {
		if cfg.Token == token {
			listedToken = cfg.Token
			break
		}
	}
	require.Equal(
		t,
		token,
		listedToken,
		"ListConfigs must return the same token SaveConfig was given",
	)

	_, err = client.DeleteConfig(
		ctx,
		connect.NewRequest(&icsproxyv1.DeleteConfigRequest{
			Token: listedToken,
		}),
	)
	require.NoError(t, err)

	_, err = client.GetConfig(ctx, connect.NewRequest(&icsproxyv1.GetConfigRequest{
		Token: token,
	}))
	require.Error(t, err)
	assert.Equal(t, connect.CodeNotFound, connect.CodeOf(err))
}
